### ISSUE TITLE
No Output Generated

### ISSUE THREAD

**Issue by arishwani** [Retrospected/attire-merger#1]
Hi, 

I tried to run the script but no output is generating here is my command ran:

python attire-merger.py -json /input/*json
ATTiRE merger - converting Atomic CSV files or merging Atomic ATTiRe files into a single ATTiRe file.
I will be taking files from ./input/. But specify if you want to use the *.csv files or *.json files in this dir by using the -csv or -json flag.

![image](https://github.com/Retrospected/attire-merger/assets/33989965/e30263ce-9fcf-407e-8245-19f011431b56)

**Comment by arishwani** [comment]
I tried many different ways but nothing works. I am providing -json flag but asking me to specify it.

**Comment by Retrospected** [comment]
remove the path in your command, the ./input/ is hardcoded

`python attire-merger.py -json` 
should do the trick..

**Comment by arishwani** [comment]
Thank you that worked @Retrospected.
